### ISSUE TITLE
 RangeError: Maximum call stack size exceeded using Collection.find

### ISSUE THREAD

**Issue by iamruinous** [mafintosh/mongojs#270]
I am getting a Maximum call stack size exceeded error when doing a simple query, `find({})` on a collection with ~ 1000 records. 

```javascript
var async, col, conn, max, mongojs;

async = require('async');

mongojs = require('mongojs');

max = 1000;

conn = mongojs("localhost/testmeout");

col = conn.collection('tests');

async.times(max, function(i, next) {
  return col.insert({
    foo: "bar " + i
  }, next);
}, function() {
  return col.find({}, function(error, data) {
    if (error !== null) {
      console.error(error.stack);
    }
    return console.log(data);
  });
});
```

https://gist.github.com/iamruinous/d9c3df9faaac368659cd

```
/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

RangeError: Maximum call stack size exceeded
  at apply (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/thunky/index.js:16:28)
  at [object Object]._get (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/thunky/index.js:27:3)
  at [object Object].Cursor.next (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongojs/lib/cursor.js:30:8)
  at loop (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongojs/lib/cursor.js:57:10)
  at /Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongojs/lib/cursor.js:61:7
  at handleCallback (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb/lib/utils.js:96:12)
  at /Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb/lib/cursor.js:674:5
  at handleCallback (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb-core/lib/cursor.js:244:5)
  at nextFunction (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb-core/lib/cursor.js:762:5)
  at [object Object].Cursor.next [as _next] (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb-core/lib/cursor.js:772:3)
  at nextObject (/Users/octoblu/Projects/Octoblu/break-mongojs/node_modules/mongodb/lib/cursor.js:659:8)
```

**Comment by iamruinous** [comment]
Submitted PR to mongodb-core https://github.com/christkv/mongodb-core/pull/64

**Comment by saintedlama** [comment]
Issue should be fixed since mongodb-native was released 13h ago with your pull request changes baked in

**Comment by koalazak** [comment]
same RangeError problem here, even with mongodb-core@1.2.28
node 0.12

**Comment by hipstersmoothie** [comment]
I am having the same issue. I have updated node and npm to the latest versions. Mongodb is at mongodb-core@1.2.28 but I still get the error. The Collection I am querying has 9000+ documents in it.

**Comment by saintedlama** [comment]
Could you post the output of

    $ node --v8-options | grep -B0 -A1 stack_size

here? I'm on node.js 4.2.3 and I'm getting this result (while I cannot reproduce the error with default settings)

```
  --stack_size (default size of stack region v8 is allowed to use (in kBytes))
        type: int  default: 984

  --sim_stack_size (Stack size of the ARM64, MIPS64 and PPC64 simulator in kBytes (default is 2 MB))
        type: int  default: 2048
```

**Comment by saintedlama** [comment]
Got it - the error is reproducable even on newest mongodb-native driver https://travis-ci.org/mafintosh/mongojs/jobs/96926740

Thanks for reporting the bug. I'll prepare a fix

**Comment by saintedlama** [comment]
Fixed and tested in travis (https://travis-ci.org/mafintosh/mongojs/builds/96930519). NPM release 2.2.1 is out.

**Comment by hipstersmoothie** [comment]
Fixed, Thanks!
